[program:redis]
command=redis-server /etc/redis/redis.conf
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/redis_stdout.log
stderr_logfile=/var/log/supervisor/redis_stderr.log
startsecs=5
stopasgroup=true

[program:init_db]
command=python3 /app/init_db.py
autostart=true
autorestart=false
startsecs=0
priority=15
stdout_logfile=/var/log/supervisor/init_db_stdout.log
stderr_logfile=/var/log/supervisor/init_db_stderr.log
stopasgroup=true

[program:gunicorn]
command=gunicorn -c /app/gunicorn_config.py app:app
directory=/app
environment=REDIS_PASSWORD="S3cureP@ss2024"
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/gunicorn_stdout.log
stderr_logfile=/var/log/supervisor/gunicorn_stderr.log
startsecs=5
stopasgroup=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/nginx_stdout.log
stderr_logfile=/var/log/supervisor/nginx_stderr.log
startsecs=5
stopasgroup=true
